### ISSUE TITLE
Rotational Angles between frame 6 and 7

### ISSUE THREAD

**Issue by followthwhiterabbit** [jhavl/dkt#2]
In the manipulator Kinematics part of the notebook, between frames 6 and 7, the angle is shown to be 180 degrees around x. To be around x is pretty obvious but when I built the robot on paper using the axes selected by you, I found that angle to be -90 degrees since there is rotation around x to match the other axes(Y6 and Y7 respectively.) I am not sure if there is something I really miss out on.

**Comment by jhavl** [comment]
Hi @followthwhiterabbit, thanks for noticing this. The 180 degree angle is correct but the frame allocated to 6 was incorrect. I have fixed the graphic to reflect this.
